// <auto-generated />
namespace Pandaloan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Name));
        
        string IMigrationMetadata.Id
        {
            get { return "201407180230164_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
